#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
git lfs post-merge "$@"

# Source all config files based on what changed
declare -A arr

arr[".i3/config"]="i3-msg reload"
arr[".tmux.conf"]="tmux source-file $HOME/.tmux.conf"
arr[".vimrc"]="vim +source +qall && stty sane"
arr[".zshrc"]="source $HOME/.zshrc > /dev/null 2> /dev/null"

files_changed="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -v .wallpaper)"

for file in $files_changed; do
  # [[ $(echo ${arr["$file"]}) ]] && echo "$file changed. Running command ${arr["$file"]}" && eval "${arr["$file"]}"
  eval "${arr["$file"]}"
done
